package com.zero.dao;

import com.zero.dataobject.ItemStockDao;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ItemStockDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Apr 04 13:58:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Apr 04 13:58:14 CST 2021
     */
    int insert(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Apr 04 13:58:14 CST 2021
     */
    ItemStockDao selectByPrimaryKey(Integer id);
    ItemStockDao selectByItemId(Integer ItemId);
    //减少库存
    int decreaseStock(@Param("itemId")Integer itemId,@Param("amount") Integer amount);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Apr 04 13:58:14 CST 2021
     */
    List<ItemStockDao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Apr 04 13:58:14 CST 2021
     */
    int updateByPrimaryKey(ItemStockDao record);
}