package com.zero.dao;

import com.zero.dataobject.OrderDao;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface OrderDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Apr 04 21:14:34 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Apr 04 21:14:34 CST 2021
     */
    int insert(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Apr 04 21:14:34 CST 2021
     */
    OrderDao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Apr 04 21:14:34 CST 2021
     */
    List<OrderDao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Apr 04 21:14:34 CST 2021
     */
    int updateByPrimaryKey(OrderDao record);
}