package com.zero.dao;

import com.zero.dataobject.SequenceDao;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface SequenceDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Apr 04 22:33:10 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Apr 04 22:33:10 CST 2021
     */
    int insert(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Apr 04 22:33:10 CST 2021
     */
    SequenceDao selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Apr 04 22:33:10 CST 2021
     */
    List<SequenceDao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Apr 04 22:33:10 CST 2021
     */
    int updateByPrimaryKey(SequenceDao record);

    SequenceDao getSequeceByName(String name);
}