package com.zero.dao;

import com.zero.dataobject.userDao;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface userDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Apr 01 23:42:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Apr 01 23:42:27 CST 2021
     */
    int insert(userDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Apr 01 23:42:27 CST 2021
     */
    userDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Apr 01 23:42:27 CST 2021
     */
    List<userDao> selectAll();

    userDao selectByTelephone(String telephone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Apr 01 23:42:27 CST 2021
     */
    int updateByPrimaryKey(userDao record);
}