server:
  port: 8888
mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath:mapping/*.xml
  #开启二级缓存
  mybatis.configuration.cache-enabled: true
#控制台看到执行的SQL语句
logging:
  level:
    com:
      mapper: debug

spring:
  datasource: #数据库连接信息
    url: jdbc:mysql://123.57.220.238:3306/testspringboot?characterEncoding=utf-8
    username: root
    password: chl252599
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB #文件上传单个不能超过10MB
      max-request-size: 100MB #总上传文件不能超过100MB
